---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-sidecar
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: sidecar
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-sidecar
spec:
  replicas: 1
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/component: sidecar
      app.kubernetes.io/name: container-object-storage-interface-sidecar
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/component: sidecar
        app.kubernetes.io/name: container-object-storage-interface-sidecar
        app.kubernetes.io/version: main
    spec:
      serviceAccountName: objectstorage-sidecar-sa
      containers:
      - name: objectstorage-sample-driver
        image: quay.io/containerobjectstorage/objectstorage-sample-driver:latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        args:
        - "--listen-address=tcp://0.0.0.0:9000"
        - "--s3-endpoint=minio.default.svc:9000"
        - "--access-key=minio"
        - "--secret-key=minio123"
        envFrom:
        - secretRef:
            name: objectstorage-sidecar
      - name: objectstorage-sidecar
        image: quay.io/containerobjectstorage/objectstorage-sidecar:latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CONNECT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: objectstorage-sidecar
              key: LISTEN_ADDRESS
