---
apiVersion: v1
kind: Namespace
metadata:
  name: objectstorage-sidecar-ns
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: sidecar
    app.kubernetes.io/version: main
    app.kubernetes.io/name: container-object-storage-interface-sidecar
